name: Java Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Change this to your desired Java version
          distribution: 'adopt' # Specify the distribution, e.g., 'adopt', 'adopt@1.11', or 'adopt-hotspot'

      - name: Build JAR
        run: |
          javac HelloWorld.java
          jar cvfe HelloWorld.jar HelloWorld HelloWorld.class

      - name: Run Java Application
        run: java -jar HelloWorld.jar

